---
# Copyright 2018, Logan Vig <logan2211@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Restart changed services
  systemd:
    name: "{{ item.item.service_name | replace(' ', '_') }}.{{ (item.item.timer is defined) | ternary('timer', 'service') }}"
    state: restarted
  listen: systemd service changed
  with_items: "{{ systemd_services_result.results }}"
  when:
    - 'item.item.restart_changed | default(systemd_service_restart_changed) | bool'
    - 'item.item.state is not defined'
    - 'item.item.enabled | default(systemd_service_enabled) | bool'
    - 'item is changed'
  tags:
   - systemd-service

- name: systemd networkd restart
  systemd:
    name: "systemd-networkd"
    state: restarted
    enabled: true
